export const ROUTES = {
  HOME: '/',
  NUMBERS: '/numbers',
  NUMEROLOGY: '/numerology',
  NUMBER_DETAILS: (id) => `/numbers/${id}`,
  SEARCH: '/search',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: (id) => `/order-success/${id}`,
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  ABOUT: '/about',
  PLANS: '/plans',
  CONTACT: '/contact',
  FAQ: '/faq',
  TERMS: '/terms',
  PRIVACY: '/privacy-policy',
  REFUND: '/refund-policy',

  ACCOUNT: '/account',
  ACCOUNT_PROFILE: '/account/profile',
  ACCOUNT_ORDERS: '/account/orders',
  ACCOUNT_WISHLIST: '/account/wishlist',
  ACCOUNT_ADDRESSES: '/account/addresses',

  ADMIN: '/admin',
  ADMIN_NUMBERS: '/admin/numbers',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_COUPONS: '/admin/coupons',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_CONTACTS: '/admin/contacts',
  ADMIN_USERS: '/admin/users',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_SETTINGS: '/admin/settings',
};
